### ISSUE TITLE
client-side fuzzing

### ISSUE THREAD

**Issue by s0i37** [Cisco-Talos/mutiny-fuzzer#6]
Good day.
Is mutinu-fuzzer supporting a fuzzing of client applications?

**Comment by jspadaro** [comment]
It does not.  That was a tentative feature we never implemented.

**Comment by s0i37** [comment]
But it seems easy to implement and scope of using will more wide.

**Comment by jspadaro** [comment]
We're not opposed to the feature, just haven't gotten to it.  Feel free to implement and submit a pull request 😃

**Comment by Thiefyface** [comment]
Experiment branch does have client side fuzzing, I'll add some documentation about it in the readme.
In order to get it up and running: 
* generate a .fuzzerfile with experiment branch.
* Make sure that the setting `commsMode Server` is inside the .fuzzer file.

After that, the only real difference from normal mutiny fuzzing is that your first message in the fuzzer file needs to be `inbound` instead of `outbound`. 

Also, if you want to use decept for generating the client-side .fuzzer file, make sure to use the `--recv_first` flag.  

If you run into any issues during the course of this all, please update and we can get it worked out/fixed. Here's an example .fuzzer file if you wanna just copy/paste.


```
'''
# Directory containing any custom exception/message/monitor processors
# This should be either an absolute path or relative to the .fuzzer file
# If set to "default", Mutiny will use any processors in the same
# folder as the .fuzzer file
processor_dir default
# Number of times to retry a test case causing a crash
failureThreshold 3
# How long to wait between retrying test cases causing a crash
failureTimeout 5
# How long for recv() to block when waiting on data from server
receiveTimeout 1.0
# Whether to perform an unfuzzed test run before fuzzing
shouldPerformTestRun 1
# Protocol (udp or tcp)
proto tcp
# Port number to connect to
port 80

commsMode Server
# The actual messages in the conversation
# Each contains a message to be sent to or from the server, printably-formatted
# Note, if you want to fuzz a submessage (designated by 'more'), then that submessage must also be marked 'fuzz'
#msg(0)
inbound 'GET / HTTP/1.1'
more '\r\n'
more fuzz 'Host: [::1]:9999'
more '\r\n'
more 'User-Agent: curl/7.52.1'
more '\r\n'
more 'Accept: */*'
more '\r\n\r\n'
#msg(1)
# Truncated for brevity [^_^]
outbound fuzz 'HTTP/1.1 200 OK\r\n'
more '</html>\n'
more '\n'
'''
########END FUZZER########
#!/usr/bin/env python2
# [...]
```

**Comment by Thiefyface** [comment]
Aight, cool, closing since thumbs up and no updates.
