### ISSUE TITLE
doubt about the multiple messages fuzz logic

### ISSUE THREAD

**Issue by cq674350529** [Cisco-Talos/mutiny-fuzzer#9]
Take the following `.fuzzer` file as an example. When I define all the messages in a single `.fuzzer` file, it will fuzz both the two messages and send them in a normal case.

```
# Protocol (udp or tcp)
proto tcp

outbound '111_start'
sub fuzz '111'
sub '111_end'
inbound 'hello'
outbound '222_start'
sub fuzz '222'
sub '222_end'
inbound 'hello'
```
However, if it fails to recv response after sending the first message, an exception will occur and break the normal routine (continue to send the second message ).  Is this the right behaviour in real-world cases?

In addition, if it succeeds to fuzz and send both the two messages, since the seed keeps unchanged in a single `performRun`, the mutated data will be same for the two messages. 

Given the two points above, is it better to define each fuzzed message in a single `.fuzzer` file while keep others unfuzzed?

> PS: I mainly use the `master` branch, it seems the logic of `experiment` branch is similar to the `master` branch.

Thanks!

**Comment by jspadaro** [comment]
> However, if it fails to recv response after sending the first message, an exception will occur and break the normal routine (continue to send the second message ). Is this the right behaviour in real-world cases?

Yes.  If it can't receive a response after the first message, the server has likely hung up or is otherwise not going to process any further messages, so sending them is moot.  If the goal is to always fuzz both messages, you can simply skip the "inbound 'hello'" line. 

If for some reason you have a use case that requires continuing on regardless, you can tweak how Mutiny handles the timeout exception, but this will not be adopted as standard behavior.

> In addition, if it succeeds to fuzz and send both the two messages, since the seed keeps unchanged in a single performRun, the mutated data will be same for the two messages.

It is using the same seed, but different inputs, so they will not have the same mutated data.

> Given the two points above, is it better to define each fuzzed message in a single .fuzzer file while keep others unfuzzed?

It depends on your use case.  Generally speaking, yes, it's better to fuzz messages individually.  Typically we run many fuzzers in parallel, one for each message.

If you have reason to expect that interaction between two messages may be important for your target, it could make sense to fuzz two messages at once.
